#version: '3.9'
 
services:

#===================================================
  seq:      
    image: datalust/seq  
    container_name: 'seq'    
    volumes:
      - seq_data:/data
    restart: always
    #restart: on-failure
    environment:
      - ACCEPT_EULA=Y      
    ports:
      - 8095:80
      - 5341:5341
    #command: apikey create -t newapikey --token 12345678901234567890 -s http://seq

#===================================================
  mysql80:
    image: mysql:8.0.30
    container_name: 'mysql80'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes: 
      - ./MySql/init:/docker-entrypoint-initdb.d
      - 'mysql-database:/var/lib/mysql'

#===================================================
#  sqlpad:
#    image: sqlpad/sqlpad
#    container_name: 'sqlpad'
#    #restart: always
#    environment: 
#      SQLPAD_ADMIN: admin@uc.no
#      SQLPAD_ADMIN_PASSWORD: 83Wrw50    
#    ports:
#      - 3400:3000
#    volumes: 
#      - /sqlpad:/var/lib/sqlpad
#    #  - ./MySql/init:/docker-entrypoint-initdb.d
#    #  - 'mysql-database:/var/lib/mysql'

      

#===================================================
  activemq01:
    image: symptoma/activemq:latest
    container_name: 'activemq01'
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin 
      ACTIVEMQ_ADMIN_PASSWORD: admin

    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - 'activemqdata:/data/activemq'
      - './activemq/log:/var/log/activemq'

#===================================================
  nodeapp01:
    image: node:alpine3.15
    container_name: nodeapp01
    tty: true
    stdin_open: true
    ports:
      - 3085:85
    depends_on:
      - "mysql80"
      - "activemq01"
    volumes:
      - ./nodeapp/source:/source
      # Skal ikke mountes bruk "docker-compose up -V" etter endringer
      - '/source/node_modules'
    working_dir: /source
    # Hvorfor fungerer ikke disse, kunne vi gjort det p책 en annen m책te??
    # Hva om vi hadde brukt en Dockerfile? Kunne vi f책tt npm install til 책 bli et layer?
    # Ville det bedret tiden for oppstart av containeren?
    #command: sh -c "npm install" && "node /source/server.js"
    #command: ["sh", "/source/start.sh"]
    #command: sh -c "chmod +X /source/start.sh" && "/source/start.sh"


#===================================================
  webjob:    
    #image: "mcr.microsoft.com/dotnet/sdk:6.0"
    image: "mcr.microsoft.com/dotnet/sdk:7.0"
    container_name: csworker

    tty: true
    
    # Configuration options that are applied at build time.    
    #ports:
      #- 3000:5059
      #- 3001:7212
    
    # Set environment variables
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=compose
    depends_on:
      - "mysql80"
      - "activemq01"    
    # Mount host directories to container directories
    volumes:
      - ./cswebjob/source:/source
      # Disse skal ikke mountes bruk "docker-compose up -V" etter endringer
      - /source/Worker/obj
      - /source/Worker/bin
    #command: ["sh", "/source/start.sh"]

#===================================================
  pyrestapi:   
    container_name: pyrestapi    
    build: 
      context: ./PyRest
      dockerfile: Dockerfile   
    tty: true        # docker run -t
    # Map external port to internal port
    ports:
      - 8099:80
    volumes:
      - ./PyRest/source:/source

#===================================================
  reactspa:
    # Specify the image to start the container from
    image: node:alpine3.15
    container_name: reactspa
    tty: true
    # Expose ports (HOST:CONTAINER)
    ports:
      - 3000:3000
    # Set environment variables
    #environment:
    # Mount host directories to container directories
    volumes:
      - ./reactspa/source:/source
      - /source/reactspa/node_modules
    #command: ["sh", "/source/start.sh"]
     
volumes:
  seq_data:
  activemqdata:
  mysql-database:
