version: '3.9'
 
services:
  codeblocks:
    container_name: 'codeblocks'
    image: mzzyk/cpp
    privileged: true
    environment:
      - DISPLAY=host.docker.internal:0 
    volumes:
      - ./source:/home/dev
    
