version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - mssqldata:/var/lib/mssqlql/data
      - ./init:/usr/src/app
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
    working_dir: /usr/src/app 
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'

volumes:
  mssqldata:
