version: '3.9'

services:
  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - mariadb_testdb:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=test_db
      # login med "root"
      - MYSQL_ROOT_PASSWORD=J3zus!
      
      - MYSQL_USER=Josef
      - MYSQL_PASSWORD=Chr1st!

volumes:
  mariadb_testdb: