version: '3.9'
 
services:
  activemq:
    image: symptoma/activemq:latest
    container_name: 'activemq'
    environment:
      ACTIVEMQ_ADMIN_LOGIN=admin 
      ACTIVEMQ_ADMIN_PASSWORD=admin
      #ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      #ACTIVEMQ_ADMIN_LOGIN: admin
      #ACTIVEMQ_ADMIN_PASSWORD: password
      #ACTIVEMQ_WRITE_LOGIN: write
      #ACTIVEMQ_WRITE_PASSWORD: password
      #ACTIVEMQ_READ_LOGIN: read
      #ACTIVEMQ_READ_PASSWORD: password
      #ACTIVEMQ_JMX_LOGIN: jmx
      #ACTIVEMQ_JMX_PASSWORD: password
      #ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      #ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      #ACTIVEMQ_ENABLED_SCHEDULER: "true"
      #ACTIVEMQ_MIN_MEMORY: 512
      #ACTIVEMQ_MAX_MEMORY: 2048
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - 'activemqdata:/data/activemq'
      - './log:/var/log/activemq'

volumes:
  activemqdata:
