FROM python:3.9

RUN pip install --upgrade --force-reinstall flask && \
    pip install pytest 

# Spørsmål: hvorfor fungerer ikke dette?
# Hva måtte vi gjøre for å få det til å virke
#WORKDIR /source
#RUN pip3 install -r /source/requirements.txt

